name: Generate Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: gen-docs-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  generate-docs:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run docs generator
        run: php genarate.php
